# Generated by Django 6.0.5 on 2026-05-06 20:19

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invite_code', models.CharField(default=core.models.generate_invite_code, max_length=8, unique=True)),
                ('vip_level', models.CharField(default='VIP1', max_length=20)),
                ('credit_score', models.IntegerField(default=100)),
                ('task_progress', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_authorized', models.BooleanField(default=False)),
                ('need_authorization', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('trade_status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=20)),
                ('withdrawal_status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=20)),
                ('online_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('recent_login', models.DateTimeField(blank=True, null=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='core.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
