# Generated by Django 6.0.5 on 2026-05-06 20:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invite_code',
            field=models.CharField(default=core.models.generate_invite_code, max_length=6, unique=True),
        ),
    ]
