# Generated by Django 6.0.4 on 2026-05-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_gender_userprofile_transaction_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=20, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='vip_icons/')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('successive_order_commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('maximum_task', models.IntegerField(default=0)),
            ],
        ),
    ]
