# Generated by Django 6.0.4 on 2026-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_viplevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viplevel',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='viplevel',
            name='successive_order_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
