# Generated by Django 6.0.4 on 2026-05-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_viplevel_commission_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vip_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.viplevel'),
        ),
    ]
