# Generated by Django 6.0.4 on 2026-05-08 20:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_vip_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vip_level',
            field=models.ForeignKey(blank=True, default=core.models.get_default_vip, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.viplevel'),
        ),
    ]
