# Generated by Django 6.0.4 on 2026-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_vip_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='viplevel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
