# Generated by Django 6.0.4 on 2026-05-10 23:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_viplevel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=core.models.generate_product_id, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cover', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('score', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('goods_album_1', models.URLField(blank=True, null=True)),
                ('goods_album_2', models.URLField(blank=True, null=True)),
                ('goods_album_3', models.URLField(blank=True, null=True)),
                ('goods_album_4', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
