# Generated by Django 6.0.4 on 2026-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='viplevel',
            name='maximum_withdrawal',
            field=models.DecimalField(decimal_places=2, default=99999999, max_digits=20),
        ),
        migrations.AddField(
            model_name='viplevel',
            name='minimum_withdrawal',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=20),
        ),
    ]
