# Generated by Django 6.0.4 on 2026-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_withdrawalrequest_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
