# Generated by Django 6.0.4 on 2026-05-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='is_successive_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userorder',
            name='successive_order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
