# Generated by Django 6.0.4 on 2026-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userorder_is_successive_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('matched', 'Matched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='matched', max_length=20),
        ),
    ]
