# Generated by Django 6.0.4 on 2026-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_userorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='negative_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
