# Generated by Django 6.0.4 on 2026-05-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_luckyreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckyreward',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luckyreward',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='luckyreward',
            name='target_order_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luckyreward',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lucky_rewards', to='core.userprofile'),
        ),
    ]
