# Generated by Django 6.0.4 on 2026-05-26 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_luckyreward_completed_at_luckyreward_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luckyreward',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='luckyreward',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luckyreward',
            name='freeze_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='luckyreward',
            name='payout_jump_time',
            field=models.IntegerField(default=10, help_text='Animation countdown seconds'),
        ),
        migrations.AddField(
            model_name='luckyreward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='luckyreward',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lucky_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='luckyreward',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='luckyreward',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('need_confirm', 'Need CS Confirm'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='luckyreward',
            name='target_order_number',
            field=models.IntegerField(default=0),
        ),
    ]
