# Generated by Django 6.0.4 on 2026-05-26 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_luckyreward_options_luckyreward_claimed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='lucky_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.luckyreward'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='order_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('successive', 'Successive'), ('lucky_reward', 'Lucky Reward')], default='normal', max_length=30),
        ),
    ]
