# Generated by Django 6.0.4 on 2026-05-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_userorder_lucky_reward_userorder_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckyreward',
            name='payout_jump_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='luckyreward',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('pending', 'Pending CS Confirm'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
