# Generated by Django 6.0.4 on 2026-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_luckyreward_payout_jump_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='is_hidden_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
