# Generated by Django 6.0.7 on 2026-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_successiveorderplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='MAJOR TOM', max_length=100)),
                ('announcement', models.TextField(default='Welcome to our platform')),
                ('banner_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('banner_url', models.URLField(blank=True, max_length=1000)),
                ('online_users_value', models.CharField(default='3.015k', max_length=30)),
                ('online_users_note', models.CharField(default='+ 29% From Last Month', max_length=100)),
                ('order_completion_value', models.CharField(default='5.016k', max_length=30)),
                ('order_completion_note', models.CharField(default='171% ↑', max_length=100)),
                ('optimize_demand_value', models.CharField(default='305k', max_length=30)),
                ('optimize_demand_note', models.CharField(default='+ 160% From Last Month', max_length=100)),
                ('order_quantity_value', models.CharField(default='5.164k', max_length=30)),
                ('order_quantity_note', models.CharField(default='157% ↑', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
