# Generated by Django 6.0.7 on 2026-07-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='order_banner_url',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dkwg2x7qd/image/upload/v1775243934/download_3_gu3ks5.png', max_length=1000),
        ),
    ]
