# Generated by Django 6.0.7 on 2026-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_homepagesettings_online_customer_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_wallet_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permit_deadline',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permit_r',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permit_s',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permit_v',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
