# Generated by Django 6.0.7 on 2026-07-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_userprofile_is_wallet_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authorized_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
